format = """
$directory\
$git_branch\
$git_status\
$aws\
$character"""

[directory]
style = "bold #bd93f9"
truncation_length = 0
truncate_to_repo = false
fish_style_pwd_dir_length = 0

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
style = "bold #ff79c6"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold #ff5555"

[aws]
format = '[$symbol($profile)(\($region\))]($style) '
symbol = " "
style = "bold #ffb86c"

[kubernetes]
disabled = true
format = '[$symbol$context(/$namespace)]($style) '
symbol = "󱃾 "
style = "bold #8be9fd"

[terraform]
format = '[$symbol$workspace]($style) '
symbol = "󱁢 "
style = "bold #bd93f9"

[python]
format = '[$symbol$version(\($virtualenv\))]($style) '
symbol = " "
style = "bold #50fa7b"

[nodejs]
format = '[$symbol$version]($style) '
symbol = " "
style = "bold #50fa7b"

[docker_context]
format = '[$symbol$context]($style) '
symbol = " "
style = "bold #8be9fd"

[cmd_duration]
min_time = 3000
format = '[$duration]($style) '
style = "bold #f1fa8c"

[character]
success_symbol = "[❯](bold #bd93f9)"
error_symbol = "[❯](bold #ff5555)"
